name: Mi Primer Workflow

on: 
  push:
    branches:
      - main


jobs:
  ejemplo:
    runs-on: ubuntu-latest
    env:
      PLATAFORMA: "AWS"
      REGION: "us-east-1"
    steps:
      - name: Mostrar Información del Evento
        run: |
          echo "Repositorio: ${{ github.repository }}"
          echo "Actor: ${{ github.actor }}"
          echo "Evento: ${{ github.event_name }}"
