name: Mi Primer Workflow

on: 
  push:
    branches:
      - main


jobs:
  ejemplo:
    runs-on: ubuntu-latest
    env:
      PLATAFORMA: "AWS"
      REGION: "us-east-1"
    steps:
      - name: Mostrar API Key (No se mostrará por seguridad)
        run: |
          echo "API Key: secrets.API_KEY"
